default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: study_app
  password: "seed1388"
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: study_app_development

test:
  <<: *default
  database: study_app_test

production:
  <<: *default
  database: study_app_production
  username: study_app
  password: <%= ENV["STUDY_APP_DATABASE_PASSWORD"] %>
